jobs:
  test:
    docker:
      - image: insightinfrastructure/icon-ci:v0.3.0
    steps:
      - checkout
      - run: molecule test

version: 2.1
workflows:
  default:
    jobs:
      - test
  version: 2
